const FORGOT_REQUEST = "FORGOT_REQUEST";
const FORGOT_SUCCESS = "FORGOT_SUCCESS";
const FORGOT_FAILURE = "FORGOT_FAILURE";

export const types = {
    FORGOT_REQUEST,
    FORGOT_SUCCESS,
    FORGOT_FAILURE,
}