const GET_ANNOUNCEMENT_REQUEST = "GET_ANNOUNCEMENT_REQUEST";
const GET_ANNOUNCEMENT_SUCCESS = "GET_ANNOUNCEMENT_SUCCESS";
const GET_ANNOUNCEMENT_FAILURE = "GET_ANNOUNCEMENT_FAILURE";

export const types = {
  GET_ANNOUNCEMENT_REQUEST,
  GET_ANNOUNCEMENT_SUCCESS,
  GET_ANNOUNCEMENT_FAILURE,
}