const GET_USER_CONVERSATION_REQUEST = "GET_USER_CONVERSATION_REQUEST";
const GET_USER_CONVERSATION_SUCCESS = "GET_USER_CONVERSATION_SUCCESS";
const GET_USER_CONVERSATION_FAILURE = "GET_USER_CONVERSATION_FAILURE";
const INIT_SOCKET_SERVICE = "INIT_SOCKET_SERVICE";
const SEND_MESSAGE = "SEND_MESSAGE";
const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_CURRENT_CONVERSATION_ID = "ADD_CURRENT_CONVERSATION_ID";
const SELECT_CONVERSATION = "SELECT_CONVERSATION";
const FAILED_TO_SELECT_CONVERSATION = "FAILED_TO_SELECT_CONVERSATION";

const ADD_FEEDBACK_CONVERSATION = "ADD_FEEDBACK_CONVERSATION";
const ADD_FEEDBACK_CONVERSATION_FAILED = "ADD_FEEDBACK_CONVERSATION_FAILED";

export const types = {
  GET_USER_CONVERSATION_REQUEST,
  GET_USER_CONVERSATION_SUCCESS,
  GET_USER_CONVERSATION_FAILURE,
  INIT_SOCKET_SERVICE,
  SEND_MESSAGE,
  ADD_MESSAGE,
  ADD_CURRENT_CONVERSATION_ID,
  SELECT_CONVERSATION,
  FAILED_TO_SELECT_CONVERSATION,
  ADD_FEEDBACK_CONVERSATION,
  ADD_FEEDBACK_CONVERSATION_FAILED

}