const GET_SPONSERS_REQUEST = "GET_SPONSERS_REQUEST";
const GET_SPONSERS_SUCCESS = "GET_SPONSERS_SUCCESS";
const GET_SPONSERS_FAILURE = "GET_SPONSERS_FAILURE";

export const types = {
  GET_SPONSERS_REQUEST,
  GET_SPONSERS_SUCCESS,
  GET_SPONSERS_FAILURE,
}