const LEARN_MORE_REQUEST = "LEARN_MORE_REQUEST";
const LEARN_MORE_SUCCESS = "LEARN_MORE_SUCCESS";
const LEARN_MORE_FAILURE = "LEARN_MORE_FAILURE";

export const types = {
  LEARN_MORE_REQUEST,
  LEARN_MORE_SUCCESS,
  LEARN_MORE_FAILURE,
}